name: demo

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  testdemo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: testflow
        run: |
          whoami
          pwd
          ls -l
          cd ./scripts
          ls -l
          chmod 755 ./*
          ls -l
          ./echodemo.sh
